services:
  nats:
    image: nats:alpine
    command: [ "--js", "--sd", "/data" ]
    ports:
      - "4222:4222" # Client Connections
      - "8222:8222" # HTTP Monitoring
    volumes:
      - nats-data:/data

  engine-server:
    image: ghcr.io/maatini/bpmninja/engine-server:latest
    # build:
    #   context: .
    #   dockerfile: engine-server/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  cobra-nats:
    image: ghcr.io/maatini/cobra-nats:0.5.2
    ports:
      - "3000:3000" # Dashboard erreichbar unter http://localhost:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - nats
    # restart: unless-stopped        # optional, aber empfehlenswert

volumes:
  nats-data:
